// <auto-generated />
namespace Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class record3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(record3));
        
        string IMigrationMetadata.Id
        {
            get { return "201702210523492_record3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
